on: [pull_request]

jobs:
  build-chain:
    runs-on: ubuntu-latest
    name: Build Pull Request
    steps:
    - uses: actions/checkout@v2
    - name: Build Chain
      id: build-chain
      uses: Ginxo/github-action-build-chain@master
      with:
        parent-dependencies: 'jbpm-wb'
        child-dependencies: 'optaweb-employee-rostering'
        build-command: 'mvn clean install'
        build-command-upstream: "mvn -e -T1C clean install -DskipTests -Dgwt.compiler.skip=true -Dgwt.skipCompilation=true -Denforcer.skip=true -Dcheckstyle.skip=true -Dspotbugs.skip=true -Drevapi.skip=true"
      env:
          GITHUB_TOKEN: "${{ secrets.KIE_TOKEN }}"
